# Generated by Django 3.2.6 on 2021-08-29 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, verbose_name='Order ID')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderPaymentConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_confirmation_status', models.CharField(max_length=100, verbose_name='Order Confirmation Status')),
                ('related_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.order', verbose_name='Related order')),
            ],
            options={
                'verbose_name': 'Order Payment Confirmation',
                'verbose_name_plural': 'Order Payment Confirmations',
            },
        ),
    ]
